version: '3.8'
services:
  mongodb:
    container_name: userAPIdb
    image: mongo
    restart: unless-stopped
    env_file: ./.env.dev
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGO_LOCAL_PORT:$MONGO_DOCKER_PORT
    networks:
      - user-api-network
    volumes:
      - db:/data/db
  app-user-api:
    depends_on:
      - mongodb
    container_name: userAPI
    build:
      context: .
      dockerfile: DockerFileDev
    restart: unless-stopped
    env_file: ./.env.dev
    image: user-api
    stdin_open: true
    ports:
      - $USER_API_LOCAL_PORT:$USER_API_DOCKER_PORT
    networks:
      - user-api-network
networks:
  user-api-network:
    driver: bridge
volumes:
  db:

