'use strict';

enum ErrorType {
    USER_SERVICE_ERROR = 'USER SERVICE ERROR',
    USER_REGISTRATION_ERROR = 'USER REGISTRATION ERROR',
    USER_SIGN_IN_ERROR = 'USER SIGN IN ERROR',
    USER_UPDATE_ERROR = 'USER UPDATE ERROR',
    USER_RETRIEVAL_ERROR = 'USER RETRIEVAL ERROR'
}

export default ErrorType;
